# Generated by Django 5.1.2 on 2024-10-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author_alter_book_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_rented',
            field=models.BooleanField(default=False, help_text='Whether the book is rented or not.'),
        ),
    ]
